dashboard: Dashboard

request_access: Request Access \n (/request-access)
notifications: Organization Notifications \n (/notifications)
granted_records: Granted Records \n (/granted-records)

dashboard -> request_access
dashboard -> notifications
dashboard -> granted_records
